'use strict';
const $=id=>document.getElementById(id),world=$('world'),viewport=$('viewport');
let board={version:1,title:'My creative workspace',bg:'#f7f5fb',items:[],view:{x:90,y:80,z:1}},selected=new Set(),tool='select',clipboard=[],undo=[],redo=[],gesture=null,editingWidget=null,db,saveTimer;
const clone=x=>JSON.parse(JSON.stringify(x)),uid=()=>crypto.randomUUID(),item=id=>board.items.find(x=>x.id===id),ns='http://www.w3.org/2000/svg';
function status(s){$('status').textContent=s}function checkpoint(){undo.push(clone(board));if(undo.length>60)undo.shift();redo=[]}function changed(){render();save()}function save(){clearTimeout(saveTimer);status('Saving…');saveTimer=setTimeout(()=>{if(!db)return;const tx=db.transaction('boards','readwrite');tx.objectStore('boards').put(clone(board),'main');tx.oncomplete=()=>status('Saved locally');tx.onerror=()=>status('Save failed — export a backup')},250)}
const request=indexedDB.open('canvas-tab',1);request.onupgradeneeded=()=>request.result.createObjectStore('boards');request.onsuccess=()=>{db=request.result;const q=db.transaction('boards').objectStore('boards').get('main');q.onsuccess=()=>{if(q.result){board=q.result;$('title').value=board.title;$('bg').value=board.bg}render();status('Saved locally')}};request.onerror=()=>status('Storage unavailable — export a backup');
function svgEl(name,attrs){let el=document.createElementNS(ns,name);for(const [k,v]of Object.entries(attrs))el.setAttribute(k,v);return el}
function render(){world.replaceChildren();cleanContainers(board.items);world.style.transform=`translate(${board.view.x}px,${board.view.y}px) scale(${board.view.z})`;viewport.style.backgroundColor=board.bg;$('zoom').textContent=Math.round(board.view.z*100)+'%';$('empty').hidden=!!board.items.length;
for(const o of board.items){const el=document.createElement('div');el.className='item '+o.type+(selected.has(o.id)?' selected':'');el.dataset.id=o.id;Object.assign(el.style,{left:o.x+'px',top:o.y+'px',width:o.w+'px',height:o.h+'px'});const c=document.createElement('div');c.className='content';el.append(c);
if(o.type==='image'){const im=document.createElement('img');im.src=o.src;im.alt='Uploaded image';c.append(im);if(o.chunkyBorder){const width=Math.max(2,Math.min(32,Number(o.borderWidth)||8)),color=/^#[0-9a-f]{6}$/i.test(o.borderColor||'')?o.borderColor:'#282035';el.classList.add('chunky-image');Object.assign(c.style,{border:`${width}px solid ${color}`,boxShadow:`${Math.round(width*1.5)}px ${Math.round(width*1.5)}px 0 ${color}`})}}
else if(['text','note','sticker'].includes(o.type)){const t=document.createElement('div');t.className='text-content';t.textContent=o.text;Object.assign(t.style,{fontFamily:o.font,fontSize:o.size+'px',color:o.color,fontWeight:o.bold?'bold':'normal',background:o.type==='note'?o.fill:'transparent'});if(o.type==='sticker'){t.style.textAlign='center';t.style.fontSize=Math.min(o.w,o.h)*.78+'px'}c.append(t)}
else if(['playlist','checklist','gallery','bookmarks'].includes(o.type)){c.append(renderContainer(o));}
else if(o.type==='widget'){const frame=document.createElement('iframe');frame.src='widget.html';frame.setAttribute('sandbox','allow-scripts');frame.title='Custom widget';frame.addEventListener('load',()=>frame.contentWindow.postMessage({type:'render-widget',html:o.html,css:o.css,js:o.js},'*'));c.append(frame);const label=document.createElement('button');label.className='widget-label';label.textContent='↖ Drag widget · Double-click to interact';el.append(label)}
else{const svg=svgEl('svg',{viewBox:`0 0 ${o.vw||o.w} ${o.vh||o.h}`,preserveAspectRatio:'none'});let shape;if(o.type==='drawing'){shape=svgEl('polyline',{points:o.points.map(p=>p.join(',')).join(' '),fill:'none'})}else if(o.type==='rectangle'){shape=svgEl('rect',{x:o.stroke/2,y:o.stroke/2,width:Math.max(1,(o.vw||o.w)-o.stroke),height:Math.max(1,(o.vh||o.h)-o.stroke),fill:o.fill||'none'})}else if(o.type==='ellipse'){shape=svgEl('ellipse',{cx:(o.vw||o.w)/2,cy:(o.vh||o.h)/2,rx:Math.max(1,((o.vw||o.w)-o.stroke)/2),ry:Math.max(1,((o.vh||o.h)-o.stroke)/2),fill:o.fill||'none'})}else shape=svgEl('line',{x1:o.flipX?(o.vw||o.w):0,y1:o.flipY?(o.vh||o.h):0,x2:o.flipX?0:(o.vw||o.w),y2:o.flipY?0:(o.vh||o.h)});for(const[k,v]of Object.entries({stroke:o.color,'stroke-width':o.stroke,'stroke-linecap':'round','stroke-linejoin':'round',opacity:o.opacity||1}))shape.setAttribute(k,v);svg.append(shape);c.append(svg)}
if(selected.has(o.id))for(const pos of ['nw','n','ne','e','se','s','sw','w']){const h=document.createElement('div');h.className='handle '+pos;h.dataset.handle=pos;el.append(h)}world.append(el)}
syncImageBorder();$('undo').disabled=!undo.length;$('redo').disabled=!redo.length;
}
function point(e){const r=viewport.getBoundingClientRect();return{x:(e.clientX-r.left-board.view.x)/board.view.z,y:(e.clientY-r.top-board.view.y)/board.view.z}}
function add(o){checkpoint();o={id:uid(),x:120,y:100,w:280,h:160,...o};const r=viewport.getBoundingClientRect();o.x=(r.width/2-board.view.x)/board.view.z-o.w/2;o.y=(r.height/2-board.view.y)/board.view.z-o.h/2;board.items.push(o);selected=new Set([o.id]);setTool('select');changed();return o}
function setTool(t){tool=t;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));viewport.style.cursor=t==='hand'?'grab':t==='select'?'default':'crosshair';$('hint').textContent=t==='select'?'Select and drag · Drag handles to resize · Shift-click for multiple selection':t==='hand'?'Drag to pan the workspace':'Draw on the canvas · Your drawing becomes a movable, resizable object'}
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
viewport.onpointerdown=e=>{if(document.body.classList.contains('clean-view'))return;if(e.button!==0&&e.button!==1)return;if(e.target.closest('[contenteditable=true]')||e.target.closest('.container-controls')||e.target.closest('.interactive')&&!e.target.closest('.widget-label')&&!e.target.dataset.handle)return;const p=point(e),el=e.target.closest('.item');if(tool==='hand'||e.button===1||e.altKey){gesture={kind:'pan',x:e.clientX,y:e.clientY,v:clone(board.view)};viewport.setPointerCapture(e.pointerId);return}
if(tool!=='select'){checkpoint();const draw=['pen','pencil','marker'].includes(tool),stroke=+$('thickness').value;const o={id:uid(),type:draw?'drawing':tool,x:p.x,y:p.y,w:1,h:1,vw:1,vh:1,color:$('color').value,stroke,opacity:tool==='marker'?.35:tool==='pencil'?.65:1,fill:$('fill').checked?$('color').value:null,points:[[stroke,stroke],[stroke+.01,stroke+.01]]};board.items.push(o);selected=new Set([o.id]);gesture={kind:'draw',id:o.id,start:p,points:[p],draw};render()}
else if(el){const id=el.dataset.id;if(e.shiftKey&&!e.target.dataset.handle){selected.has(id)?selected.delete(id):selected.add(id);render();return}if(!selected.has(id))selected=new Set([id]);checkpoint();gesture={kind:e.target.dataset.handle?'resize':'move',handle:e.target.dataset.handle,id,start:p,original:board.items.filter(o=>selected.has(o.id)).map(clone)};syncProperties();render()}
else{selected.clear();render();return}viewport.setPointerCapture(e.pointerId)};
viewport.onpointermove=e=>{if(!gesture)return;const g=gesture,p=point(e);if(g.kind==='pan'){board.view.x=g.v.x+e.clientX-g.x;board.view.y=g.v.y+e.clientY-g.y;render();return}const dx=p.x-g.start.x,dy=p.y-g.start.y;if(g.kind==='move'){g.original.forEach(old=>Object.assign(item(old.id),{x:old.x+dx,y:old.y+dy}))}else if(g.kind==='resize'){const old=g.original.find(x=>x.id===g.id),o=item(g.id),h=g.handle;let x=old.x,y=old.y,w=old.w,ht=old.h;if(h.includes('e'))w=Math.max(20,w+dx);if(h.includes('s'))ht=Math.max(20,ht+dy);if(h.includes('w')){w=Math.max(20,old.w-dx);x=old.x+old.w-w}if(h.includes('n')){ht=Math.max(20,old.h-dy);y=old.y+old.h-ht}Object.assign(o,{x,y,w,h:ht})}else{const o=item(g.id);if(g.draw){g.points.push(p);const xs=g.points.map(p=>p.x),ys=g.points.map(p=>p.y),minX=Math.min(...xs)-o.stroke,minY=Math.min(...ys)-o.stroke;o.x=minX;o.y=minY;o.w=Math.max(2,Math.max(...xs)-minX+o.stroke);o.h=Math.max(2,Math.max(...ys)-minY+o.stroke);o.points=g.points.map(p=>[p.x-minX,p.y-minY])}else{Object.assign(o,{x:Math.min(p.x,g.start.x),y:Math.min(p.y,g.start.y),w:Math.max(2,Math.abs(dx)),h:Math.max(2,Math.abs(dy)),flipX:dx<0,flipY:dy<0})}o.vw=o.w;o.vh=o.h}render()};
viewport.onpointerup=()=>{if(gesture){if(gesture.kind==='draw')setTool('select');gesture=null;save()}};viewport.onpointercancel=viewport.onpointerup;
viewport.ondblclick=e=>{if(document.body.classList.contains('clean-view'))return;const el=e.target.closest('.item');if(!el)return;const o=item(el.dataset.id);if(o.type==='widget'){el.classList.toggle('interactive');el.querySelector('.widget-label').textContent=el.classList.contains('interactive')?'Interacting · Double-click here to move':'↖ Drag widget · Double-click to interact';return}editText(el,o)};
function editText(el,o){if(['playlist','checklist','gallery','bookmarks'].includes(o.type)){editContainer(o);return}if(!['text','note'].includes(o.type))return;checkpoint();const t=el.querySelector('.text-content');t.contentEditable='true';t.focus();t.onblur=()=>{o.text=t.textContent;t.contentEditable='false';save()};t.onkeydown=e=>{e.stopPropagation();if(e.key==='Escape')t.blur()}}
function syncProperties(){const o=item([...selected][0]);if(!o)return;if(o.color)$('color').value=o.color;if(o.font)$('font').value=o.font;if(o.size)$('fontSize').value=o.size;if(o.stroke)$('thickness').value=o.stroke;$('bold').classList.toggle('active',!!o.bold)}
function modify(fn){if(!selected.size)return;checkpoint();board.items.filter(o=>selected.has(o.id)).forEach(fn);changed()}
$('color').onchange=()=>modify(o=>o.color=$('color').value);$('thickness').oninput=()=>{$('widthLabel').value=$('thickness').value};$('thickness').onchange=()=>modify(o=>o.stroke=+$('thickness').value);$('fill').onchange=()=>modify(o=>{if(['rectangle','ellipse'].includes(o.type))o.fill=$('fill').checked?$('color').value:null});$('font').onchange=()=>modify(o=>o.font=$('font').value);$('fontSize').onchange=()=>modify(o=>o.size=Math.max(8,Math.min(300,+$('fontSize').value||28)));$('bold').onclick=()=>{modify(o=>o.bold=!o.bold);syncProperties()};$('bg').onchange=()=>{checkpoint();board.bg=$('bg').value;changed()};$('title').onchange=()=>{board.title=$('title').value;save()};
$('text').onclick=()=>add({type:'text',text:'Double-click to write',font:$('font').value,size:+$('fontSize').value,color:$('color').value,h:100});$('note').onclick=()=>add({type:'note',text:'An idea worth keeping…',font:$('font').value,size:24,color:'#322442',fill:'#eedaff',w:240,h:220});
function remove(){if(!selected.size)return;checkpoint();board.items=board.items.filter(o=>!selected.has(o.id));selected.clear();changed()};$('delete').onclick=remove;
function copy(){clipboard=board.items.filter(o=>selected.has(o.id)).map(clone)}function paste(){if(!clipboard.length)return;checkpoint();const objs=clipboard.map(o=>({...clone(o),id:uid(),x:o.x+30,y:o.y+30}));board.items.push(...objs);selected=new Set(objs.map(o=>o.id));clipboard=objs.map(clone);changed()}
$('duplicate').onclick=()=>{copy();paste()};$('front').onclick=()=>{checkpoint();board.items=[...board.items.filter(o=>!selected.has(o.id)),...board.items.filter(o=>selected.has(o.id))];changed()};$('back').onclick=()=>{checkpoint();board.items=[...board.items.filter(o=>selected.has(o.id)),...board.items.filter(o=>!selected.has(o.id))];changed()};$('edit').onclick=()=>{const o=item([...selected][0]);if(!o)return;if(o.type==='widget')openWidget(o);else editText(world.querySelector(`[data-id="${o.id}"]`),o)};
function history(back){const from=back?undo:redo,to=back?redo:undo;if(!from.length)return;to.push(clone(board));board=from.pop();selected.clear();$('title').value=board.title;$('bg').value=board.bg;changed()}$('undo').onclick=()=>history(true);$('redo').onclick=()=>history(false);
addEventListener('keydown',e=>{if(document.body.classList.contains('clean-view'))return;if(e.target.closest('.container-controls')||e.target.matches('input,textarea,select,[contenteditable=true]')||$('widgetDialog').open||$('stickerDialog').open)return;const mod=e.ctrlKey||e.metaKey;if(mod&&['c','v','x','z','y','a','d'].includes(e.key.toLowerCase())){if(e.key.toLowerCase()!=='v'||clipboard.length)e.preventDefault();switch(e.key.toLowerCase()){case'c':copy();break;case'v':paste();break;case'x':copy();remove();break;case'z':history(!e.shiftKey);break;case'y':history(false);break;case'a':selected=new Set(board.items.map(o=>o.id));render();break;case'd':copy();paste()}}else if(['Delete','Backspace'].includes(e.key)){e.preventDefault();remove()}else if(e.key==='Escape'){selected.clear();setTool('select');render()}else if(e.key.startsWith('Arrow')&&selected.size){e.preventDefault();const d=e.shiftKey?10:1;modify(o=>{o.x+=e.key==='ArrowLeft'?-d:e.key==='ArrowRight'?d:0;o.y+=e.key==='ArrowUp'?-d:e.key==='ArrowDown'?d:0})}});
async function loadImages(files){for(const f of files){if(!f.type.startsWith('image/'))continue;const src=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)});const im=new Image();im.src=src;try{await im.decode();const w=Math.min(400,im.naturalWidth||200);add({type:'image',src,w,h:w*(im.naturalHeight||200)/(im.naturalWidth||200)})}catch{status('Could not read image')}}}
$('image').onclick=()=>$('files').click();$('files').onchange=e=>{loadImages(e.target.files);e.target.value=''};viewport.ondragover=e=>{e.preventDefault()};viewport.ondrop=e=>{e.preventDefault();loadImages(e.dataTransfer.files)};addEventListener('paste',e=>{if(e.target.closest('.container-controls')||e.target.matches('input,textarea,[contenteditable=true]'))return;const files=[...e.clipboardData.files];if(files.length){e.preventDefault();loadImages(files)}else{const text=e.clipboardData.getData('text/plain');if(text&&!clipboard.length){e.preventDefault();add({type:'text',text,font:$('font').value,size:28,color:$('color').value})}}});
const stickers=[['⭐','star sparkle'],['🌟','star glow'],['✨','sparkles stars'],['✦','star diamond'],['💖','heart pink'],['💜','heart purple'],['💕','hearts'],['🖤','heart black'],['🦋','butterfly'],['🌸','flower blossom'],['🌷','flower tulip'],['🌿','plant leaf'],['🍄','mushroom'],['🌈','rainbow'],['☁️','cloud'],['🌙','moon'],['☀️','sun'],['🔥','fire'],['💧','water drop'],['❄️','snow'],['🐈','cat animal'],['🐕','dog animal'],['🐸','frog animal'],['🦊','fox animal'],['🐝','bee animal'],['👽','alien'],['👻','ghost'],['💀','skull'],['🎀','bow ribbon'],['💿','disc cd music'],['📼','tape video'],['📷','camera'],['🎧','headphones music'],['🎮','game controller'],['🪩','disco ball'],['🍒','cherry fruit'],['🍓','strawberry fruit'],['🍰','cake'],['☕','coffee'],['🧋','bubble tea'],['💬','speech chat'],['❗','exclamation'],['✔️','check'],['📌','pin'],['🔮','crystal ball'],['🧷','safety pin'],['🗝️','key'],['🪄','magic wand'],['🧠','brain'],['👁️','eye'],['🛸','ufo space'],['🚀','rocket space']];
function showStickers(){const q=$('stickerSearch').value.toLowerCase();$('stickerGrid').replaceChildren();stickers.filter(([s,n])=>n.includes(q)||s.includes(q)).forEach(([s,n])=>{const b=document.createElement('button');b.textContent=s;b.title=n;b.onclick=()=>{add({type:'sticker',text:s,w:100,h:100,size:80,font:'Arial',color:'#272035'});$('stickerDialog').close()};$('stickerGrid').append(b)})}$('stickers').onclick=()=>{showStickers();$('stickerDialog').showModal()};$('stickerSearch').oninput=showStickers;$('uploadSticker').onclick=()=>{$('stickerDialog').close();$('files').click()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
function openWidget(o){editingWidget=o?.id||null;$('htmlCode').value=o?.html||'<button id="count">Clicked 0 times</button>';$('cssCode').value=o?.css||'body { display:grid; place-items:center; height:100vh; background:#f0dbff; font-family:Arial; }\nbutton { padding:16px; border:2px solid #272035; border-radius:12px; background:#fff; font-size:20px; cursor:pointer; }';$('jsCode').value=o?.js||'let n = 0;\ndocument.querySelector("#count").onclick = (e) => { e.target.textContent = `Clicked ${++n} times`; };';$('saveWidget').textContent=o?'Update widget':'Add widget';$('widgetDialog').showModal()}$('widget').onclick=()=>openWidget();$('saveWidget').onclick=()=>{const data={html:$('htmlCode').value,css:$('cssCode').value,js:$('jsCode').value};if(editingWidget){checkpoint();Object.assign(item(editingWidget),data);changed()}else add({type:'widget',w:340,h:240,...data});$('widgetDialog').close()};
function zoom(z,cx=viewport.clientWidth/2,cy=viewport.clientHeight/2){const v=board.view,n=Math.max(.2,Math.min(4,z)),wx=(cx-v.x)/v.z,wy=(cy-v.y)/v.z;v.x=cx-wx*n;v.y=cy-wy*n;v.z=n;render();save()}viewport.addEventListener('wheel',e=>{e.preventDefault();if(e.ctrlKey||e.metaKey){const r=viewport.getBoundingClientRect();zoom(board.view.z*Math.exp(-e.deltaY*.003),e.clientX-r.left,e.clientY-r.top)}else{board.view.x-=e.deltaX;board.view.y-=e.deltaY;render();save()}},{passive:false});$('zoomIn').onclick=()=>zoom(board.view.z*1.2);$('zoomOut').onclick=()=>zoom(board.view.z/1.2);$('home').onclick=()=>{board.view={x:90,y:80,z:1};render();save()};$('grid').onclick=()=>{const off=viewport.style.backgroundImage==='none';viewport.style.backgroundImage=off?'':'none';$('grid').textContent='Grid: '+(off?'on':'off')};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(board,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(board.title.replace(/[^a-z0-9]/gi,'-')||'canvas')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};$('import').onclick=()=>$('restoreFile').click();$('restoreFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const b=JSON.parse(await f.text());if(b.version!==1||!Array.isArray(b.items)||!b.view||typeof b.title!=='string'||b.items.some(o=>!['text','note','sticker','image','widget','drawing','rectangle','ellipse','line','playlist','checklist','gallery','bookmarks'].includes(o.type)||![o.x,o.y,o.w,o.h].every(Number.isFinite)))throw Error('Invalid board');checkpoint();board=b;selected.clear();$('title').value=b.title;$('bg').value=b.bg;changed()}catch{status('Invalid backup file')}e.target.value=''};
render();

function toggleEditor(){
 const before=viewport.getBoundingClientRect();
 const hidden=document.body.classList.toggle('clean-view');
 const after=viewport.getBoundingClientRect();
 // Keep the board anchored on screen while the viewport expands/contracts.
 board.view.x+=before.left-after.left;board.view.y+=before.top-after.top;
 world.style.transform=`translate(${board.view.x}px,${board.view.y}px) scale(${board.view.z})`;
 $('toggleEditor').textContent=hidden?'◉ Show controls':'◉ Hide controls';
 $('toggleEditor').setAttribute('aria-label',hidden?'Show editor controls':'Hide editor controls');
 $('toggleEditor').setAttribute('aria-pressed',String(hidden));
 document.querySelectorAll('dialog[open]').forEach(d=>d.close());
 if(document.activeElement?.isContentEditable)document.activeElement.blur();
 save();
}
$('toggleEditor').onclick=toggleEditor;
addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='h'){e.preventDefault();toggleEditor()}});

function syncImageBorder(){const images=board.items.filter(o=>selected.has(o.id)&&o.type==='image');const active=images.length>0&&images.every(o=>o.chunkyBorder);$('imageBorder').disabled=!images.length;$('borderColor').disabled=!images.length;$('borderWidth').disabled=!images.length;$('imageBorder').classList.toggle('active',active);$('imageBorder').setAttribute('aria-pressed',String(active));if(images.length){$('borderColor').value=images[0].borderColor||'#282035';$('borderWidth').value=images[0].borderWidth||8}}
$('imageBorder').onclick=()=>{const images=board.items.filter(o=>selected.has(o.id)&&o.type==='image');if(!images.length)return;const enabled=!images.every(o=>o.chunkyBorder);checkpoint();for(const o of images){o.chunkyBorder=enabled;o.borderColor=o.borderColor||$('borderColor').value;o.borderWidth=o.borderWidth||8}changed()};
$('borderColor').onchange=()=>{const color=$('borderColor').value;modify(o=>{if(o.type==='image')o.borderColor=color})};
$('borderWidth').onchange=()=>{const width=Math.max(2,Math.min(32,Number($('borderWidth').value)||8));modify(o=>{if(o.type==='image')o.borderWidth=width})};
